# Generated by Django 4.2.3 on 2023-09-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_product_name_product_category_product_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_name',
        ),
    ]
