# Generated by Django 4.2.3 on 2023-09-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
