# Generated by Django 4.2.3 on 2023-09-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_desc_product_pname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
